# Generated by Django 6.0 on 2025-12-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportsmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sportsmen_photos/')),
                ('description', models.TextField(max_length=1000)),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, unique=True)),
                ('achievement', models.TextField(help_text='Каждое достижение с новой строки')),
                ('rating', models.CharField(choices=[('red', 'Красный'), ('green', 'Зеленый'), ('diamond', 'Алмазный'), ('gold', 'Золотой')], default='green', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportsmen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
