# Generated by Django 6.0 on 2025-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmen',
            name='rating',
            field=models.CharField(choices=[('gold', 'Золотой'), ('diamond', 'Алмазный'), ('green', 'Зеленый'), ('red', 'Красный')], default='green', max_length=10),
        ),
    ]
