# Generated by Django 6.0 on 2025-12-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0003_alter_sportsmen_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmen',
            name='photo',
            field=models.ImageField(blank=True, default='sportsmen_photos/default.jpg', null=True, upload_to='sportsmen_photos/'),
        ),
    ]
