# Generated by Django 6.0 on 2025-12-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0004_alter_sportsmen_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsmen',
            name='number',
        ),
        migrations.AlterField(
            model_name='sportsmen',
            name='photo',
            field=models.ImageField(default='sportsmen_photos/default.jpg', upload_to='sportsmen_photos/'),
        ),
    ]
