# Generated by Django 6.0 on 2025-12-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0005_remove_sportsmen_number_alter_sportsmen_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmen',
            name='description',
            field=models.TextField(),
        ),
    ]
