# Generated by Django 6.0 on 2025-12-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0006_alter_sportsmen_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsmen',
            name='rank',
            field=models.CharField(choices=[('green', 'Зелёный'), ('red', 'Красный'), ('diamond', 'Алмазный'), ('gold', 'Золотая вершина')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='sportsmen',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
