# Generated by Django 6.0 on 2025-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0007_sportsmen_rank_alter_sportsmen_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsmen',
            name='rank',
        ),
        migrations.AddField(
            model_name='sportsmen',
            name='division',
            field=models.CharField(choices=[('red', 'Красный'), ('green', 'Зелёный'), ('diamond', 'Алмазный'), ('gold', 'Золотая вершина')], default='green', max_length=10),
        ),
    ]
