# Generated by Django 6.0 on 2025-12-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmen', '0008_remove_sportsmen_rank_sportsmen_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmen',
            name='division',
            field=models.CharField(choices=[('gold', 'Золотой'), ('diamond', 'Алмазный'), ('green', 'Зеленый'), ('red', 'Красный')], default='green', max_length=10),
        ),
    ]
