# Generated by Django 6.0 on 2025-12-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportsmen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_rating', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_sportsmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_fights', to='sportsmen.sportsmen')),
                ('second_sportsmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_fights', to='sportsmen.sportsmen')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='sportsmen.sportsmen')),
            ],
            options={
                'verbose_name': 'Fight',
                'verbose_name_plural': 'Fights',
                'ordering': ['-date'],
            },
        ),
    ]
