# Generated by Django 6.0 on 2025-12-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='sport',
            field=models.CharField(choices=[('Shaxbox', 'Шахбокс'), ('Karate', 'Каратэ'), ('Box', 'Бокс')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
