# Generated by Django 6.0 on 2025-12-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0002_fight_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.RemoveField(
            model_name='fight',
            name='sport',
        ),
        migrations.AddField(
            model_name='fight',
            name='count_rounds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='fight.sport')),
            ],
            options={
                'verbose_name': 'Sport section',
                'verbose_name_plural': 'Sport sections',
                'unique_together': {('sport', 'name')},
            },
        ),
        migrations.AddField(
            model_name='fight',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fights', to='fight.sportsection'),
            preserve_default=False,
        ),
    ]
